ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    publish_tf: true
    sensor_timeout: 0.1
    two_d_mode: false 
    transform_time_offset: 0.0
    print_diagnostics: true
    debug: true

    map_frame: map             
    odom_frame: odom            
    base_link_frame: zed_camera_link 
    world_frame: odom 
    odom0: /zed/zed_node/odom # Optional: ZED odometry (if used)
    imu0: /zed/zed_node/imu/data
    odom0_config: [false, false, false, 
               false, false, false, 
               true,  true,  true,
               false, false, false, 
               false, false, false]
    imu0_config:  [false, false, false, 
                  true,  true,  true, 
                  false, false, false,
                  true,  true,  true,
                  false, false, false]

    odom0_differential: false
    imu0_differential: false

   