# RTAB-Map configuration

subscribe_depth:        true
subscribe_rgbd:         false
subscribe_stereo:       false
subscribe_scan:         false
subscribe_scan_cloud:   false
subscribe_user_data:    false
subscribe_odom_info:    false
visual_odometry:        false
log_level:              "warn"
rtabmap_args:           "--delete_db_on_start"
rgb_topic:              "/zed/zed_node/rgb/image_rect_color"
depth_topic:            "/zed/zed_node/depth/depth_registered"
camera_info_topic:      "/zed/zed_node/rgb/camera_info"
frame_id:               "base_link"
approx_sync:            true
wait_imu_to_init:       false
#imu_topic:              "/zed/zed_node/imu/data"
qos:                    1
#odom_topic:             "/zed/zed_node/odom"  # RTAB-Map will publish odometry
publish_tf_odom:        false
namespace:              '/'
topic_queue_size:       30
queue_size:             30  # Reduce queue size if you're not experiencing delays
database_path:      "~/.ros/rtabmap.db"
tf_tolerance:           1.0
map_frame_id:   "map"
odom_frame_id:  "odom"
odom_tf_angular_variance:  0.001
odom_tf_linear_variance:   0.001
tf_delay:       10.2  # Reduce if possible, but monitor for extrapolation errors
publish_tf:     false

odom_sensor_sync:               false  # Disable if not strictly needed
wait_for_transform_duration:    0.2  # Reduce if possible, but monitor for errors

scan_normal_k:  0